### ISSUE TITLE
several issues found when twilio / node newbie installs

### ISSUE THREAD

**Issue by bkathler** [TwilioDevEd/ivr-phone-tree-node#2]
Hi !

Thanks for your code I did get it to work but here are some issues I found along the way:

1 - the twilio phone url must be a post not a get
2 - views/layout.jade can not find:
   -  link(rel='stylesheet', type='text/css', href='/stylesheets/style.css')
   -   script(src='/javascripts/modernizr-2.6.2.js')

I copied the modernizr file into the views folder and changed my layout.jade to this:

doctype html
html
  head
    meta(charset='utf-8')
    meta(name='viewport', content='width=device-width, initial-scale=1.0')
    title IVR Phone Tree
    script(src='modernizr-2.6.2.js')
  body
    .container.body-content
      block content
      footer
        | Made with 
        i.fa.fa-heart
        |  by your pals
        |    
        a(href='http://www.twilio.com') @twilio

then it worked

**Comment by nebtrx** [comment]
Hi @bkathler. Thanks for trying this application :). I reviewed your feedback and I found that only one of the three issues mentioned was really an issue. Lets have a look:

1. The Twilio Voice Url use indeed POST. It's explained in the [tutorial](//www.twilio.com/docs/tutorials/walkthrough/ivr-phone-tree/node/express#1).
1. The [`style.css`](//github.com/TwilioDevEd/ivr-phone-tree-node/blob/78d2c4aef561f09effb2e92e631ccc1ee76299ca/public/stylesheets/style.css) is in the `public/stylesheets` directory and it's accesible from the view. I've just tested right now.
1. The inclusion of `modernizr.js` file was indeed an **issue**.Thanks for pointing that out :+1:. The application don't require it, in fact, I've just removed it.

Thanks for your time and if you have any other issues or question, don't hesitate to ping me. Happy coding!
